import { Urbanist, Poppins,Raleway,Playfair_Display } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/providers/ThemeProvider";
import 'react-date-range/dist/styles.css'
import 'react-date-range/dist/theme/default.css'
import TanstackProvider from "@/providers/TanstackProvider";
// Urbanist font
const urbanist = Urbanist({
  variable: "--font-urbanist",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});
const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});
const playFairDisplay = Playfair_Display({
  variable: "--font-playfairdisplay",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

// Poppins font
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${urbanist.variable} ${poppins.variable} antialiased`}
      >
        <TanstackProvider>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
        </TanstackProvider>
      </body>
    </html>
  );
}
